model:
  vision:
    channels: [8, 16, 32]
    kernels: [6, 6, 6]
    strides: [3, 3, 3]
    paddings: [3, 3, 3]
  
  mlp:
    mlp_hidden_dim: 256
    n_mlp_layers: 0  #MLPの隠れ層の数

  policy:
    hidden_dim: 256 #RNNの隠れ層の次元
  
  latent_obs_dim: 250 #潜在変数の次元(obs=観測情報)

  diffusion:
    n_obs_steps: 2 #何ステップ過去として入れるか
    horizon: 16 #未来のステップ数
    n_action_steps: 6 #実際に行動するステップ数

data:
  split_ratio: [0.7, 0.2, 0.1]
  batch_size: 10
  seed: 0
  sequence_length: 10 #シーケンスの長さ

train:
  learning_rate: 0.001
  weight_decay: 1.0e-6
  kl_loss_scale: 10
  epoch: 500


logging:
  best_epoch_path: result/dim_8/model/best_epoch.yaml

wandb:
  project_name: 'Kensyu_3_new'
  train_name: 'World_Model_1'
  config:
    device: 'cuda:0'

run:
  steps: 50
  fps: 5

parameters:
  dreamer:
    stochastic_size: 30 #stochastic:確率論的
    deterministic_size: 200 #deterministic:決定論的
    embedded_state_size: 250 #埋め込み状態の次元 エンコーダの出力次元に合わせる
    rssm:
      recurrent_model:
        hidden_size: 200
        activation: "ELU"
      transition_model:
        hidden_size: 200
        num_layers: 2
        activation: "ELU"
        min_std: 0.1
      representation_model:
        hidden_size: 200
        num_layers: 2
        activation: "ELU"
        min_std: 0.1 

operation:
  device: "mps"